### ISSUE TITLE
consistent format for discount env vars

### ISSUE THREAD

**Issue by pom11** [blocknetdx/eth-payment-processor#20]
```Traceback (most recent call last):
  File "/app/manager/main.py", line 12, in <module>
    from util.eth_payments import Web3Helper
  File "/app/manager/util/__init__.py", line 11, in <module>
    discount_ablock = float((100 - os.environ.get('DISCOUNT_ABLOCK', 20))/100)
TypeError: unsupported operand type(s) for -: 'int' and 'str'```

**Comment by ConanMishler** [comment]
Can't test this thoroughly until issue #123 in `exrproxy-env` is fixed.
